version: "3.8"

services:
  backend:
    image: samarthdave23/stayngo-backend:latest
    ports:
      - "5001:5001"
    # env_file:
    #   - ./backend/.env
    environment:
     - SUPABASE_URL=https://upfvuyzknlandrmjoolz.supabase.co
     - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwZnZ1eXprbmxhbmRybWpvb2x6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzczNDgyNTQsImV4cCI6MjA5MjkyNDI1NH0.YqUAwZQiJvzkqx6HV5pkZX2-Gw1slcorRIiSOg1cobM
    restart: always

  frontend:
    image: samarthdave23/stayngo-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5001/api
    depends_on:
      - backend
    restart: always

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_logs:/opt/sonarqube/logs
    restart: always

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   # Docker socket 
    restart: always

volumes:
  sonar_data:
  sonar_logs:
  jenkins_home: