sonar.projectKey=stayngo
sonar.projectName=StayNGo
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.token=sqp_db26997b83e6822bc6513335ce004e54531e644c
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.next/**,**/venv/**,**/__pycache__/**,**/migrations/**
sonar.python.version=3